apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-scanner
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.scanner.replicas }}
  selector:
    matchLabels:
      app: neuvector-scanner
  template:
    metadata:
      labels:
        app: neuvector-scanner
    spec:
      containers:
        - name: scanner
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/scanner:{{ .Values.image.tag }}"
