apiVersion: v1
kind: Service
metadata:
  name: neuvector-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: neuvector-controller
  ports:
    - name: https
      port: {{ .Values.service.uiPort }}
      targetPort: 8443
