namespace: suse-security

image:
  repository: neuvector/neuvector
  #repository: registry.suse.com/neuvector
  tag: "5.3.0"

controller:
  replicas: 3
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

enforcer:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

scanner:
  replicas: 1

service:
  type: ClusterIP
  uiPort: 8443

ingress:
  enabled: false
  className: nginx
  host: suse-security.example.com

rbac:
  create: true

global:
  imagePullSecrets: []  
#global:
  #imagePullSecrets:
    #- name: suse-registry-secret
